#!/bin/ash
#
# This script make sure that the various keys are created for the sshd server
# and the user for authorized keys.  To use launch the script in an `exec` function.
#
# ```
# podman exec --interactive --tty --user root alpine /usr/bin/bastion-setup ansible
# ```

echo "Bastion Container Service - Setup"
if [ ! -d /opt/bastion/etc/ssh ] ; then
 /bin/mkdir -p /opt/bastion/etc/ssh
 /usr/bin/ssh-keygen -A -N '' -f /opt/bastion/
fi
if [ ! -f /opt/bastion/ssh/authorized_keys ] ; then
 /bin/mkdir -p /opt/bastion/auth
 /usr/bin/ssh-keygen -f /opt/bastion/auth/rsa_id -N '' -t rsa
 /bin/mkdir -p /opt/bastion/ssh
 /bin/cp /opt/bastion/auth/rsa_id.pub /opt/bastion/ssh/authorized_keys
 /bin/chown -R "$1":"$1" /opt/bastion/ssh
 /bin/chmod 0700 /opt/bastion/ssh
 /bin/chmod 0600 /opt/bastion/ssh/authorized_keys
fi
